import Foundation

/// Reads ESPN's free public scoreboard API (no key). Only scores and game status are used — odds are generated by `OddsEngine`.
nonisolated enum ESPNClient {
    private static let base = "https://site.api.espn.com/apis/site/v2/sports"

    private static let session: URLSession = {
        let config = URLSessionConfiguration.default
        config.requestCachePolicy = .reloadIgnoringLocalCacheData
        config.timeoutIntervalForRequest = 12
        return URLSession(configuration: config)
    }()

    @concurrent
    static func scoreboard(for league: League) async throws -> [Game] {
        guard let path = league.espnPath, let url = URL(string: "\(base)/\(path)/scoreboard") else { return [] }
        let (data, _) = try await session.data(from: url)
        let board = try JSONDecoder().decode(ScoreboardDTO.self, from: data)
        return (board.events ?? []).compactMap { event in
            guard let competition = event.competitions.first else { return nil }
            return makeGame(eventID: event.id, league: league, date: event.date, competition: competition)
        }
    }

    /// Looks up a single game — used to settle bets on games that have dropped off the current scoreboard.
    @concurrent
    static func game(eventID: String, league: League) async throws -> Game? {
        guard let path = league.espnPath, let url = URL(string: "\(base)/\(path)/summary?event=\(eventID)") else { return nil }
        let (data, _) = try await session.data(from: url)
        let summary = try JSONDecoder().decode(SummaryDTO.self, from: data)
        guard let competition = summary.header.competitions.first else { return nil }
        return makeGame(eventID: eventID, league: league, date: competition.date ?? "", competition: competition)
    }

    private static func makeGame(eventID: String, league: League, date: String, competition: CompetitionDTO) -> Game? {
        guard
            let homeDTO = competition.competitors.first(where: { $0.homeAway == "home" }),
            let awayDTO = competition.competitors.first(where: { $0.homeAway == "away" }),
            let status = competition.status
        else { return nil }

        let state: GameState
        switch status.type.name {
        case "STATUS_POSTPONED": state = .postponed
        case "STATUS_CANCELED", "STATUS_CANCELLED", "STATUS_ABANDONED", "STATUS_FORFEIT": state = .canceled
        default:
            switch status.type.state {
            case "in": state = .live
            case "post": state = .final
            default: state = .scheduled
            }
        }

        return Game(
            eventID: eventID,
            league: league,
            start: parseDate(date) ?? .distantFuture,
            state: state,
            home: makeTeam(homeDTO),
            away: makeTeam(awayDTO),
            homeScore: Int(homeDTO.score ?? "") ?? 0,
            awayScore: Int(awayDTO.score ?? "") ?? 0,
            period: status.period ?? 0,
            clock: status.clock ?? 0,
            statusDetail: status.type.shortDetail ?? status.type.detail ?? ""
        )
    }

    private static func makeTeam(_ dto: CompetitorDTO) -> Team {
        let t = dto.team
        let logo = t.logo ?? t.logos?.first?.href
        return Team(
            id: t.id,
            abbreviation: t.abbreviation ?? String((t.displayName ?? "TBD").prefix(3)).uppercased(),
            name: t.shortDisplayName ?? t.name ?? t.displayName ?? "TBD",
            fullName: t.displayName ?? t.name ?? "TBD",
            colorHex: t.color ?? "5A6475",
            altColorHex: t.alternateColor,
            logoURL: logo.flatMap(URL.init(string:)),
            record: dto.records?.first(where: { $0.type == "total" })?.summary ?? dto.records?.first?.summary
        )
    }

    /// ESPN sends "2026-09-25T00:15Z" (no seconds), which ISO8601DateFormatter rejects by default.
    private static func parseDate(_ string: String) -> Date? {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        for format in ["yyyy-MM-dd'T'HH:mm'Z'", "yyyy-MM-dd'T'HH:mm:ss'Z'", "yyyy-MM-dd'T'HH:mm:ssZ"] {
            formatter.dateFormat = format
            if let date = formatter.date(from: string) { return date }
        }
        return nil
    }
}

// MARK: - DTOs (only the fields we use)

private nonisolated struct ScoreboardDTO: Decodable {
    let events: [EventDTO]?
}

private nonisolated struct SummaryDTO: Decodable {
    struct Header: Decodable { let competitions: [CompetitionDTO] }
    let header: Header
}

private nonisolated struct EventDTO: Decodable {
    let id: String
    let date: String
    let competitions: [CompetitionDTO]
}

private nonisolated struct CompetitionDTO: Decodable {
    let date: String?
    let status: StatusDTO?
    let competitors: [CompetitorDTO]
}

private nonisolated struct StatusDTO: Decodable {
    struct Kind: Decodable {
        let name: String
        let state: String
        let detail: String?
        let shortDetail: String?
    }
    let clock: Double?
    let period: Int?
    let type: Kind
}

private nonisolated struct CompetitorDTO: Decodable {
    struct Record: Decodable {
        let type: String?
        let summary: String?
    }
    let homeAway: String
    let score: String?
    let team: TeamDTO
    let records: [Record]?
}

private nonisolated struct TeamDTO: Decodable {
    struct Logo: Decodable { let href: String }
    let id: String
    let abbreviation: String?
    let displayName: String?
    let shortDisplayName: String?
    let name: String?
    let color: String?
    let alternateColor: String?
    let logo: String?
    let logos: [Logo]?
}
